# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# filter-dissolve.py
# Created on: 2016-01-13 10:34:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: filter-dissolve <Input_Features> <Filter_Expression> <Output_Features> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Features = arcpy.GetParameterAsText(0)
if Input_Features == '#' or not Input_Features:
    Input_Features = "D:\\p\\NHN\\yt_nhn.gdb\\Dataset\\NHN_HD_WATERBODY_2" # provide a default value if unspecified

Filter_Expression = arcpy.GetParameterAsText(1)
if Filter_Expression == '#' or not Filter_Expression:
    Filter_Expression = "lakeId1 NOT LIKE ''" # provide a default value if unspecified

Output_Features = arcpy.GetParameterAsText(2)
if Output_Features == '#' or not Output_Features:
    Output_Features = "D:\\p\\NHN\\yt_nhn.gdb\\Regions\\Named_Lakes" # provide a default value if unspecified

# Local variables:
nameId_not_empty = "arc_Named_Lakes"
Dissolve_Field_s_ = "permanency;lakeId1;lakeName1;waterDefinitionText"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Input_Features, nameId_not_empty, Filter_Expression, "", "OBJECTID OBJECTID VISIBLE NONE;SHAPE SHAPE VISIBLE NONE;nid nid VISIBLE NONE;validityDate validityDate VISIBLE NONE;acquisitionTechnique acquisitionTechnique VISIBLE NONE;datasetName datasetName VISIBLE NONE;planimetricAccuracy planimetricAccuracy VISIBLE NONE;provider provider VISIBLE NONE;completelyCover completelyCover VISIBLE NONE;waterDefinition waterDefinition VISIBLE NONE;isolated isolated VISIBLE NONE;permanency permanency VISIBLE NONE;geographicalNameDB geographicalNameDB VISIBLE NONE;lakeId1 lakeId1 VISIBLE NONE;lakeId2 lakeId2 VISIBLE NONE;riverId1 riverId1 VISIBLE NONE;riverId2 riverId2 VISIBLE NONE;lakeName1 lakeName1 VISIBLE NONE;lakeName2 lakeName2 VISIBLE NONE;riverName1 riverName1 VISIBLE NONE;riverName2 riverName2 VISIBLE NONE;idDate idDate VISIBLE NONE;nameDate nameDate VISIBLE NONE;waterDefinitionText waterDefinitionText VISIBLE NONE;SHAPE_Length SHAPE_Length VISIBLE NONE;SHAPE_Area SHAPE_Area VISIBLE NONE")

# Process: Dissolve
arcpy.Dissolve_management(nameId_not_empty, Output_Features, Dissolve_Field_s_, "", "MULTI_PART", "DISSOLVE_LINES")

